# Site settings
title: BitcoinCasinoDeutsch.de - gute BTC-Casinos, die deutsch sprechen
email: 
description: > # this means to ignore newlines until "baseurl:"
  Testberichte, Meinungen und Erfahrungen rund um deutschsprachige Casinos, die Bitcoin akzeptieren
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bitcoincasinodeutsch.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: cayman
